api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header

    title: 'BiLeMo'

    version: '1.0.0'

    http_cache:
        etag: true
        max_age: 50

    enable_swagger_ui: true

    enable_docs: true

    enable_swagger: true

    formats:
        jsonhal:
          mime_types: ['application/hal+json']
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']

    collection:
        order_parameter_name: '_order'
        pagination:
            items_per_page: 10
            page_parameter_name: page
            client_enabled: true
            enabled_parameter_name: pagination

