api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header

    title: 'BiLeMo'

    version: '1.0.0'

    http_cache:
        etag: true
        max_age: 10

    enable_swagger_ui: true

    enable_nelmio_api_doc: true

    enable_docs: true

    enable_swagger: true

    graphql:
        enabled: true
        graphiql:
            enabled: true

    formats:
        jsonld:
            mime_types: ['application/ld+json']
        json:
            mime_types: ['application/json']
        html:
            mime_types: ['text/html']

    collection:
        pagination:
            items_per_page: 10
            page_parameter_name: page

