api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']


    title: 'BiLeMo'

    version: '1.0'

    http_cache:
        etag: true

    enable_swagger_ui: true

    api_platform:
        collection:
            pagination:
                items_per_page: 10
