security:

    providers:
        in_database:
            entity:
                class: App\Entity\Client
                property: username

    encoders:
        App\Entity\Client:
            algorithm: bcrypt

    firewalls:
        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api/
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/api
            provider: in_database

    access_control:
        - { path: ^/api/login_check, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/phones,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/client,       roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/api/user,       roles: IS_AUTHENTICATED_FULLY }

