security:

    providers:
        in_database:
            entity:
                class: App\Entity\Client
                property: username

    encoders:
        App\Entity\Client:
            algorithm: bcrypt

    firewalls:

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/api/
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/api
            provider: in_database



    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/phones, roles: ROLE_ADMIN, methods:[GET,POST,DELETE,PUT]}
        - { path: ^/api/phones, roles: ROLE_USER, methods: GET}
        - { path: ^/api/client, roles: ROLE_ADMIN, methods:[GET,POST,DELETE,PUT] }
        - { path: ^/api/user, roles: ROLE_ADMIN, methods:[GET,POST,DELETE,PUT] }
        - { path: ^/api/user, roles: ROLE_USER, methods:[GET,POST,DELETE,PUT] }

